### ISSUE TITLE
public.dhe.ibm.com no longer exists

### ISSUE THREAD

**Issue by cattywampus** [WASdev/ci.chef.wlp#47]
When running the kitchen tests I get the following error:

```
         Errno::ECONNREFUSED
         -------------------
         Failed to open TCP connection to public.dhe.ibm.com:80 (Connection refused - connect(2) for "public.dhe.ibm.com" port 80)

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/wlp/libraries/utils.rb:67:in `autoVersionUrls'
           /tmp/kitchen/cache/cookbooks/wlp/recipes/_archive_install.rb:31:in `from_file'
           /tmp/kitchen/cache/cookbooks/wlp/recipes/default.rb:56:in `from_file'
           /tmp/kitchen/cache/cookbooks/wlp_test/recipes/start.rb:18:in `from_file'
           /tmp/kitchen/cache/cookbooks/wlp_test/recipes/basic.rb:18:in `from_file'

         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/wlp/libraries/utils.rb:

          60:
          61:      def chown(file)
          62:        FileUtils.chown(user, group, file)                                                                                                                                     63:      end
          64:
          65:      def autoVersionUrls
          66:        require 'open-uri'
          67>>       version_yml  = YAML::load(open(@node['wlp']['archive']['version_yaml']))
          68:
          69:        use_beta = @node['wlp']['archive']['use_beta']
          70:
          71:        runtime_uri = ''
          72:        version_yml.each do |key, value|
          73:          if !use_beta && key.start_with?('8.5')
          74:            runtime_uri = ::URI.parse(value["uri"])
          75:            # The newest version is the first one listed so break out after the first
          76:            break
```

When I try accessing http://public.dhe.ibm.com in the browser, sure enough it's not accessible. Is there a new public location that this attribute can be defaulted to so the tests pass? Having this in place will make it easier for me to make a few pull requests with confidence that I didn't break any of the tests.

**Comment by cattywampus** [comment]
This might be a more pervasive problem. None of the downloads at [WASDev](https://developer.ibm.com/wasdev/downloads/) are working.

**Comment by cattywampus** [comment]
This hasn't been a problem for a long time and was likely a short-lived outage.
